apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{app.name}}
  name: {{app.name}}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{app.name}}
  type: ClusterIP